"""Modifies Preferences Table

Revision ID: 0d5245bb884f
Revises: c43bfa3ca751
Create Date: 2024-04-27 15:49:30.208391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5245bb884f'
down_revision = 'c43bfa3ca751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preference', schema=None) as batch_op:
        batch_op.alter_column('preference_value2',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preference', schema=None) as batch_op:
        batch_op.alter_column('preference_value2',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###
